### ISSUE TITLE
Inline Content Recommendations v1

### ISSUE THREAD

**Issue by sarahyablok** [lytics/pathforajs#119]
With the migration of the datalio inline element toggle from the jstag to pathfora, and since the topic of inline recommendations have come up quite recently, I thought that it might be useful to implement content recommendations in a similar style for us to use on our marketing site, and as a potential early option for customers with dev resources. Here's the idea for a template:

``` html
<div data-lioblock="block1" data-liorecommend="www.getlytics.com/blog/posts/*">
  <div data-liotype="image"></div>
  <a data-liotype="url"><h2 data-liotype="title"></h2></a>
  <p data-liotype="description"></p>
</div>
```

Each recommendation block has a unique `data-lioblock` name. `The data-liorecommend` attribute provides a string url pattern to be used as a basic filter for the recommendation. In the future we could implement this filter in a better way, but to start we would only support url filtering. Multiple recommendation blocks with the same `data-liorecommend` attribute will be filled with results from a single same api response, so as not to repeat content. `data-liotype` dictates the content that should be filled in via javascript.

- `image` = primary image of the document. (Set as background image if on a `div` or the `src` attribute if on an image.
- `url` = url of the document. (Set as `href` attribute if on a link, or innerHTML if on a div).
- `title` = title of the document.
- `description` = meta description of the document.

We will also support a default option should the recommendation request fail.

Here's an example (with minimal styles applied) to show what these recommendations make look like.

<img width="1225" alt="screen shot 2016-07-05 at 12 35 07 pm" src="https://cloud.githubusercontent.com/assets/5973633/16597307/096629bc-42ad-11e6-84df-ac54ad83a2c0.png">

**Comment by araddon** [comment]
Awesome!

**Comment by araddon** [comment]
wow, the huge week continues, great job.
