### ISSUE TITLE
Support new recommendation filters

### ISSUE THREAD

**Issue by sarahyablok** [lytics/pathforajs#131]
Content recommendation modal configs can now be expanded to support the following new fields:

- `topics`  - topics to which the recommendations should be constrained
- `rollups`  -rollup topics to which the recommendations should be constrained
- `from`  - start date (published) of recommendations to use
- `to`  - end date (published) of recommendations to use
- `path`  - url path of documents to filter
- `domain` - domain of acceptable documents to return
- `rank`  - method of ranking to use, currently {popular|affinity|recent}
- `visited` - whether to show urls that the user has seen

we should maintain support for raw ql as well.

To start I will add support for these filters for modals only, we should rethink the way we support inline recommendations or possibly wait for content collections.

**Comment by araddon** [comment]
Also would like to add support for "Named Content Collections"  https://github.com/lytics/lio/issues/7678

**Comment by sarahyablok** [comment]
@araddon Agreed, since the PR for this will probably get merged with in the next week or so I'll probably make a new ticket for content collections once they are fully supported.
