### ISSUE TITLE
Form Progress Event(s)

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#144]
There are some valuable use cases that are powered by targeting users that have began to fill out a lead capture but then have abandoned. Lets explore a few ways that we can emit meaningful events to track progress.

For V1 lets keep it simple by emitting a new event as soon as any user controlled field contains > 0 characters. This would show they had intent but would ignore the amount of progress they made (e.g. 2 out of 3 fields) which is probably irrelevant for most initial use cases. 

Likewise, it might be interesting to track hover states as well. Users that have moused over the "submit" or "CTA" buttons but did not click, might be an interesting way to build an audience of users likely to convert?

**Comment by sarahyablok** [comment]
Here's a list of events I'm planning on adding and their additional tracking values (feel free to comment with suggested changes/additions):

## Hover Over CTA
**pf-widget-event**: `hover`
**pf-widget-action**: `confirm`

(Do we want to track cancel/close hovers? Doesn't seem too relevant to a marketer, but you never know...)

## Form Element Focus
**pf-widget-event**: `focus`
**pf-widget-action**: `input.name`

## Form Element Started (input has at least one character)
**pf-widget-event**: `form_status`
**pf-widget-action**: `started`

(Do we want to track the field name here?)
