### ISSUE TITLE
Additional Positions for Slide Out

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#151]
A customer has requested top left / right positions for the slide out widgets. More details outlined here https://github.com/lytics/customerprojects/issues/46. 

Should be a fairly simple core update to support those positions since they are already supported by the button widgets.

**Comment by aaronschmick** [comment]
Praetorian Digital has upcoming campaigns next month where they need this positioning available to work with their site. I'm not sure where this ticket sits on dev timeline, but if we could move it up in priority that would be helpful to the customer. thx.

**Comment by sarahyablok** [comment]
I'll add this to "up-next" on our board, and hopefully get to it next week.
