### ISSUE TITLE
Support for More Advanced Form Building

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#169]
Its a pretty common theme / request to support alternate inputs and/or input types within our personalization widgets. there are a few things to consider when determining what the solution is here:

1) Flexibility. We want to make sure we support the most common input types (text input, text area, select, button, radio, etc). We can likely get away with rolling this out at separate time as opposed to one big push but definitely worth considering all the options. 

2) Organization. Users are somewhat used to dragging and dropping or moving fields around. Right now our forms are in a fixed order. Need to figure out a simple set of requirements for positioning. 

3) Reporting. Everything done with Pathfora should roll neatly into Lytics. This might be as simple as using an existing map for all new fields or something to that effect but we definitely want to know what this looks like through the lens of the Lytics dashboard before moving forward. 

4) Third party vendors. One thing we can explore is integrating tools. I personally think that we should support form building natively. Our styles are already pretty flexible as far as size and positioning. It really just comes down to the config. Third party tools require another step and their own set of potential challenges. Either way we should explore all options before diving in head first. 

All that said lets first come up with a definitive list of requirements. @sarahyablok I think you and I can probably chat for 30 minutes this week and hammer out that based on what customers have asked / what is coming down the pipe. Then we can branch off and figure out the best approach.

**Comment by markhayden** [comment]
Potential third parties to consider via @aaron: 

* https://formbuilder.online/
* http://minikomi.github.io/Bootstrap-Form-Builder/
* http://www.alpacajs.org/

**Comment by markhayden** [comment]
after reviewing https://formbuilder.online/ again, the schema this generates isn't too bad / could be a good place to start.

**Comment by sarahyablok** [comment]
Here are the form elements we plan to support:

- checkboxes
- radio buttons
- text input
- textarea
- select box

Feel free to comment/add if I'm missing any.

**Comment by markhayden** [comment]
probably worth mentioning checkbox / radio groups as well (e.g. select one of the following)

**Comment by markhayden** [comment]
another thing to think about, probably, is validation. might be worth allowing for a regex validation for each field or something like that. could be overkill but probably a thing that will come up.

e.g. i want to collect birthday and keep the dates all formatted.

**Comment by DingoEatingFuzz** [comment]
One that I have heard a lot for progressive profiling is a simple Yes/No.

Are you a veteran?
[Yes] [No]

Have you made a donation before?
[Yes] [No]

**Comment by DingoEatingFuzz** [comment]
Here is the collection of inputs that Google Forms has, for reference:

![image](https://cloud.githubusercontent.com/assets/174740/22753310/8cfbadda-edf0-11e6-8272-de17118ca1ce.png)

**Comment by sarahyablok** [comment]
@DingoEatingFuzz Yes/No should definitely be covered by the radio buttons. Thanks for the google form reference! 👍 

@markhayden I agree, validation is something I have been thinking about. Right now our `required` setting will only check if the field has been filled out or not. The example case you're talking about though, makes me think that maybe we should include a date field? I could see birthday being a commonly requested field. And if we have a date input type it would allow us to standardize the date formatting in Lytics.

**Comment by DingoEatingFuzz** [comment]
A form with radio buttons requires selecting an option and submitting the form. That's 2x the required actions of a single button.

**Comment by sarahyablok** [comment]
@markhayden Here's some wip examples for you to review.

Using the https://formbuilder.online/ schema to generate a form with the following config:

``` javascript
      var form = pathfora.Form({
        id: 'survey',
        layout: 'slideout',
        headline: 'Please complete this survey',
        msg: 'Tell us about yourself and some of your favorite things.',
        formElements: [
          {
            'type': 'input',
            'name': 'name',
            'placeholder': 'Your Name'
          },
          {
            'type': 'select',
            'placeholder': 'What\'s your favorite animal?',
            'name': 'favorite_animal',
            'values': [
              {
                'label': 'Cat',
                'value': 'cat',
              },
              {
                'label': 'Dog',
                'value': 'dog'
              },
              {
                'label': 'Horse',
                'value': 'horse'
              }
            ]
          },
          {
            'type': 'radio-group',
            'label': 'What\'s your favorite color?',
            'name': 'favorite_color',
            'values': [
              {
                'label': 'Red',
                'value': 'red',
              },
              {
                'label': 'Blue',
                'value': 'blue'
              },
              {
                'label': 'Green',
                'value': 'green'
              }
            ]
          },
          {
            'type': 'checkbox-group',
            'label': 'Which ice cream flavors do you like the most?',
            'name': 'ice_cream_flavors',
            'values': [
              {
                'label': 'Vanilla',
                'value': 'vanilla',
              },
              {
                'label': 'Chocolate',
                'value': 'chocolate'
              },
              {
                'label': 'Strawberry',
                'value': 'strawberry'
              }
            ]
          },
          {
            'type': 'textarea',
            'name': 'comments',
            'placeholder': 'Any more comments?'
          }
        ],
        okMessage: 'Send',
        cancelMessage: 'Cancel',
      });
```


Results in the following form, which I have filled out below:

<img width="413" alt="screen shot 2017-02-09 at 12 02 45 pm" src="https://cloud.githubusercontent.com/assets/5973633/22800991/03d62ab4-eec0-11e6-8094-988fbd5abbe6.png">

Tracking wise, this is what the object sent to Lytics looks like currently:

<img width="256" alt="screen shot 2017-02-09 at 12 03 56 pm" src="https://cloud.githubusercontent.com/assets/5973633/22801080/4bf809c0-eec0-11e6-917e-10040cde7a69.png">


all the form data will be contained in a `map[string]value` called `pf-custom-form`

**Comment by sarahyablok** [comment]
After a couple iterations on the new styles for form validation/required fields. This is what I've come up with. Placing here for reference:

<img width="416" alt="screen shot 2017-02-10 at 2 49 37 pm" src="https://cloud.githubusercontent.com/assets/5973633/22847426/9c918e6a-efa1-11e6-9810-03ea8e2db476.png">

We'll be adding two new color options for users to customize this feature: `required` and `requiedText`
