### ISSUE TITLE
Content Recommendation AST Support

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#170]
In addition to segment slug and ql for the recommendation collection we need to support a string of AST. Api support will be added in support of this change with https://github.com/lytics/lio/issues/9064. 

Should be able to just add ast to the existing payload and pass that as a param just like ql. In the case where any combination of the three exist the following priority should be taken:

1) Slug
2) AST
3) QL

No idea what would happen if you use a different definition for all three on a single recommendation but that seems bad :)

**Comment by DingoEatingFuzz** [comment]
A have a couple questions about this.

1. Why a string of an AST? The AST API is already defined as a JSON-safe representation, so why not let it be a POJO?
2. Is this necessary? It would only be necessary if you expect a person authoring a pathfora widget to also want to use an AST. It wouldn't hurt to support it, but it doesn't seem like a necessary thing.

**Comment by markhayden** [comment]
1. yah thats fine...i am format neutral and you are much closer to using AST than me.
2. probably not but it adding safeguards seems to not be a bad thing?
