### ISSUE TITLE
Docs Update

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#172]
Just a reminder to update our docs for the following:

* [ ] New top-left and top-right positions.
* [ ] Content recommendations via AST

**Comment by sarahyablok** [comment]
These are now all merged. I'll keep this ticket open as a reminder to deploy the docs with the next pathfora deploy.

**Comment by markhayden** [comment]
woot

**Comment by sarahyablok** [comment]
docs are now up to date.
