### ISSUE TITLE
escape dynamically generated regexp

### ISSUE THREAD

**Issue by humanchimp** [lytics/pathforajs#176]
In places like this:

https://github.com/lytics/pathforajs/blob/develop/src/pathfora.js#L251

We should be escaping the `className`, in case it contains RegExp syntax. In webadmin, we use a utility like this:

```javascript
export default function escapeRegExp(s) {
  return String(s).replace(/[\\^$*+?.()|[\]{}]/g, '\\$&');
}
```

*Updated*: I fixed the link to point to the correct line.

**Comment by sarahyablok** [comment]
This was added a while ago. Closing issue now.
