### ISSUE TITLE
Personalize campaign modal size issue - safari only

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#206]
migrated from https://github.com/lytics/lio/issues/9842

Customer: Internal (found in Support). 
AID: 2421
Priority: medium
Impact: The size of this modal will likely mean users do not enter the information requested

Steps to reproduce:

Create a new customer campaign of collect leads type
Using Safari browser (ha!) navigate to the url the campaign is targeting
Results:

The campaign modal does not size to the requested fields, users have to scroll through.

Screencast: https://www.screencast.com/t/LhAgQ8epLhY

Edit: Racing Post & Access Intelligence have since reported this issue
Zendesk tickets: [#353](https://lytics.zendesk.com/agent/tickets/353) & [#354](https://lytics.zendesk.com/agent/tickets/354)

**Comment by sarahyablok** [comment]
Ah I believe this behavior was added accidentally with a [recent PR](https://github.com/lytics/pathforajs/pull/201) I'll go ahead and see if I can fix this.
