### ISSUE TITLE
Event Tracking - Google Analytics

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#21]
### Objective
Right now Lytics tracking is built in, which is great and useful. However, in the wild Lytics is likely to not be the only end point as it relates to tracking. Most of our customers use at a minimum one or two other forms of web tracking in addition to Lytics, such as Google Analytics. There needs to be some preliminary method to support this.

### Scope
For simplicity sake the first version will not require a config, we will simply check to see if the `ga` object exists, if it does we will assume they want events passed there and fire them off. Down the road this might be something controlled by a config, so keep that in mind.

On any action, everywhere jstag.send is fired, there will need to be an additional call for these integrations, Google Analytics initially.

That check will ensure the `ga` object exists, if it does it will fire an event per Googles event docs (https://developers.google.com/analytics/devguides/collection/analyticsjs/events).

```
ga('send', 'event', 'Lytics', 'Action Name', '', {nonInteraction: true});
```

The fifth param can just be an empty string for now as I don't think we have any details on the actions at this time.

Future integrations, not a part of this ticket but just food for thought will likely be Omniture, Marketo Munchkin, Mixpanel, KISS Metrics, Keen.io, Intercom, etc.

### Tasks
* [x] Ability to fire `ga('send')` event along side `jstag.send` events.
* [x] Integrated into all existing actions.

**Comment by mjurczyk** [comment]
@markhayden PR submitted for this one, please review

**Comment by dylo0** [comment]
@markhayden @mjurczyk - I'll do code reviews for this and A/B testing tomorrow, and merge it into develop branch. 
On Friday I'll ask our QA for checking develop branch and merge it into master after successful review

**Comment by markhayden** [comment]
awesome. thanks @dylo0.

**Comment by markhayden** [comment]
tested this one in development and all looked good. added a small pr to append the widget id to the label we send to GA just to facilitate better reporting but going to go ahead and close this.
