### ISSUE TITLE
If I use more than one regex url exclude in a campaign the exclude no longer works

### ISSUE THREAD

**Issue by matthewgodfrey** [lytics/pathforajs#212]
Customer: motoring.co.uk
AID: 2312
Priority: medium

Steps to reproduce:

1. Add a regex to exclude a specific url within a campaign
2. Test to make sure the exclude is working
3. Add a second regex to exclude a different url

Results:

Neither url excludes work

Screencast:https://www.screencast.com/t/LNph4fc9

**Comment by sarahyablok** [comment]
Ok, so by default our display conditions use OR logic. So the example: (pages that do not include `landscapes`) OR (pages that do not include `black-and-white`) = all pages. For multiple excludes we would have to use the exclude setting, which is not currently supported in our UI. http://lytics.github.io/pathforadocs/display_conditions/#urlcontains
