### ISSUE TITLE
Don't Send GA Events by Default

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#213]
Right now we are passing GA events if the GA object is defined. For a few users this is becoming a problem because they are nearing their cap for GA events before going to the enterprise tier. I am thinking that we need to just turn this off by default, not sure anyone is using it anyway and then have a flag in the config to turn it back on. We can then turn that on for all customers that have not blacklisted the GA dimensions integration when we generate the personalization campaign config from the Lytics platform.

**Comment by ddrazba-lytics** [comment]
@markhayden this all merged and g2g?

**Comment by markhayden** [comment]
correct. this is all merged, supported by the main api and in production.
