### ISSUE TITLE
Content Recommendation URL Bug

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#224]
It seems like sporadically the click through URL on a content recommendation modal formats the URL improperly. Meaning that once in a while it appends the domain twice. Assume this is something simple and I can share specific customer examples for testing...just don't want to share on the public PathforaJS repo.

**Comment by markhayden** [comment]
Tracked down the issue, can put in a fix in the morning. It only effects recommendations that we are pulling out of the session storage. The first time a recommendation loads (from the api) everything works fine. For any subsequent recommendation of that same piece of content that we pull from the session cache we are double appending the domain.

**Comment by araddon** [comment]
thx for finding mark

**Comment by sarahyablok** [comment]
@markhayden Did we confirm that this is fixed by https://github.com/lytics/pathforajs/pull/220 which hasn't been deployed yet? Or is it something else?

**Comment by markhayden** [comment]
pretty sure that will fix it. we should deploy and test. was hoping we could get the email regex thing merged as part of the release as well tho.
