### ISSUE TITLE
Personalize Campaigns/Previews Not working for TheStreet (2229)

### ISSUE THREAD

**Issue by ddrazba-lytics** [lytics/pathforajs#237]
Customer: TheStreet
AID:2229

Summary: Personalize campaigns and previews aren't working on TheStreet.com.  Manually invoking a pathfora modal from the command line does not work either.

Preview not working: https://www.thestreet.com/quote?lytics_variation_preview_id=c49f4ebfe57425cf46b15020a7da86d5

Manual Pathfora not working:
```
var module = new pathfora.Form({
  id: 'modal-image',
  layout: 'modal',
  headline: 'Sign Up!',
  msg: 'Submit this form to get updates',
  variant: 2,
  image: '../../../../assets/lion.jpg'
});
```

```
pathfora.initializeWidgets([module]);
```

<img width="1154" alt="screen shot 2017-08-25 at 12 54 18 pm" src="https://user-images.githubusercontent.com/15821696/29731209-72e9f566-8998-11e7-9e0f-4eb37b6c0197.png">
<img width="1164" alt="screen shot 2017-08-25 at 12 53 56 pm" src="https://user-images.githubusercontent.com/15821696/29731210-72ec8f2e-8998-11e7-9ac7-f42cee7de17d.png">

**Comment by aaronschmick** [comment]
Hey guys, can you provide a summary or just sentence describing what was causing the issue, so I can create a statement for the customer.
