### ISSUE TITLE
Don't use the window load event listener to reinitialize prioritized widgets

### ISSUE THREAD

**Issue by sarahyablok** [lytics/pathforajs#246]

**Comment by aaronschmick** [comment]
our users at TheStreet noted that they saw a dip in generated leads and impressions in these campaigns again as previously noted with this ticket:

Fi-Strat Final Promo
Top 5 Stocks, Lead Generation	
Best Stock 2017, Lead Generation
AAP Win Back

Sarah, did anything change on your end with testing to cause the above campaigns to drop in reach?

**Comment by sarahyablok** [comment]
https://github.com/lytics/pathforajs/issues/272
