### ISSUE TITLE
Alter Bar Position Naming

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#27]
Can we make some small changes to the naming of bar position options? Since the SDK is in support of developers its counter intuitive to have `top-fixed` actually result in an absolute position while `top-scrolling` is a fixed position.

Lets:
`top-fixed` --> `top-absolute`
`top-scrolling` --> `top-fixed`
`bottom-scrolling` --> `bottom-fixed`

**Comment by mjurczyk** [comment]
@markhayden PR ready for this one https://github.com/lytics/pathforajs/pull/28

**Comment by markhayden** [comment]
awesome. will review today, thanks @mjurczyk
