### ISSUE TITLE
Customers with Social Login enabled via Pathfora should fail gracefully

### ISSUE THREAD

**Issue by curtis-gross** [lytics/pathforajs#296]
The current state is to break Pathfora when the social login code was removed recently: lytics/pathforajs#294

Which leaves anyone who was using the Pathfora SDK in a state of error:
![screen shot 2018-04-27 at 9 04 35 am](https://user-images.githubusercontent.com/6655371/39376543-e2a34914-4a06-11e8-9328-930dacf7bcbc.png)

**Comment by curtis-gross** [comment]
@markhayden / @sarahyablok - this closable ?

**Comment by sarahyablok** [comment]
Yes, we removed social login.
