### ISSUE TITLE
Recommend content campaign will not preview if document has no meta description.

### ISSUE THREAD

**Issue by shindakun** [lytics/pathforajs#298]
Issue: If the content has a blank description modal will not display.

![image](https://user-images.githubusercontent.com/319128/40933239-b8bf391c-67e5-11e8-8786-89e263c38bb1.png)
![image](https://user-images.githubusercontent.com/319128/40933259-c454e29a-67e5-11e8-86f9-f1cac3af55c4.png)

Expected: Content should display even if the description field happens to be blank.

**Comment by kristinh12** [comment]
Fix for this was merged awhile back, going to close.
