### ISSUE TITLE
expiration manager against localStorage payload

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#346]
- cull expired data
- extend active date: on `.getItem`, update the expiration date

**Comment by humanchimp** [comment]
should we expose an option to control the expiration TTL? I believe we discussed this and I wanted to do so. I believe the current TTL (based on cookies) is 1 year.

**Comment by markhayden** [comment]
yah we could definitely surface the ability to control. likewise we talked about reducing the default to 30 days and then pushing that 30 days each time a widget is initialized

e.g. dormant widgets will persist for 30 days by default

**Comment by humanchimp** [comment]
what do we think about an API like the below for parameterizing expiration:

```javascript
new pathfora.Message({
   // ...elided
   ttl: '1y' // or '1m' or '30d' and so on
});
```

**Comment by markhayden** [comment]
thats probably fine. could also nest it under the display conditions since that is more tightly coupled with what it impacts....also could, in theory, make a case for it to be coupled with specific display conditions if you wanted one to persist longer but that is probably more granular than would ever be necessary.

**Comment by markhayden** [comment]
lets break the config option into its own feature ticket
