### ISSUE TITLE
Exit Intent not working with Scroll Percentage Display Condition

### ISSUE THREAD

**Issue by shindakun** [lytics/pathforajs#408]
@sarahyablok We may have a regression since it looks like this was addressed in #367. It is being reported again with a nearly identical description.

**Comment by cbrock** [comment]
Confirmed that `exitIntent` and `scrollPercentageToDisplay` display options are working correctly in conjunction with each other, i.e. a user would need to scroll `x`% down the page _then_ trigger exit intent behavior for a modal to appear.

The confusion seems to have resulted from expecting or wanting this `AND` behavior to function more like `OR` which is not currently supported.

However, a semi-related bug was found while investigating which should be resolved by #427.
