### ISSUE TITLE
links broken in documentation

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#420]
- http://lytics.github.io/pathforadocs/customization/css/ a broken link: - 
  - http://lytics.github.io/layouts/modal.md#variant
- http://lytics.github.io/pathforadocs/api/config/ a broken link: 
  - http://lytics.github.io/api/methods.md#initializewidgets
- http://lytics.github.io/pathforadocs/customization/css/ a broken link: 
  - http://lytics.github.io/layouts/modal.md
- http://lytics.github.io/pathforadocs/customization/css/ a broken link: 
  - http://lytics.github.io/types/gate.md

**Comment by cbrock** [comment]
Closed via https://github.com/lytics/pathforajs/pull/432
