### ISSUE TITLE
[FR] Add ability to split description on "。" for Japanese text.

### ISSUE THREAD

**Issue by shindakun** [lytics/pathforajs#446]
There has been a request to update the description trimming to also split on `。` (`\xE3\x80\x82`) in addition to a "space".

https://github.com/lytics/pathforajs/blob/b4e4f03b630c7a437e44a8f11ca30972c7a0c47a/src/rollup/widgets/recommendations/setup-widget-content-unit.js#L124

There was a case of a content slide out that ended up with a description similar to:

`Word...`

The actual text had a single space between two words written in English and the rest was separated by `。` where appropriate.

Ping me and I can share the actual text and screenshots if need be.

(Note to self: 4847)

**Comment by sarahyablok** [comment]
@shindakun Can you send me the additional context here? Specific use case and screenshots.

**Comment by sarahyablok** [comment]
Chatted with @shindakun and we are going to opt to use the `descriptionLength` setting for this case: http://lytics.github.io/pathforadocs/content_recommend/#recommend
