### ISSUE TITLE
Only expire items from localStorage added by pathforajs

### ISSUE THREAD

**Issue by daveythesaint** [lytics/pathforajs#598]
As the subject suggests, this request is to only expire items from localStorage that have been added by pathforajs.

**Comment by ayana-perry-lytics** [comment]
@ashyablok Hello Ash, Is there an update on this issue?  Thanks

**Comment by ashyablok** [comment]
Yep! We merged the code need to deploy it. I'll reopen the issue until then.

**Comment by ashyablok** [comment]
@ayana-perry-lytics this has been deployed
