### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by shindakun** [lytics/pathforajs#621]
When trying to demonstrate an inline modal with targeting I found that I could not. I receive an error:

```
pathfora.min.js:formatted:493 Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at window.pathfora.no [as addCallback] (pathfora.min.js:formatted:493:23)
    at pathfora.min.js:formatted:2215:15
    at HTMLDocument.t (pathfora.min.js:formatted:234:13)
```

Spoke to @humanchimp around issue and it appears to be a bug.

Repro steps: 

1. Open new incognito window
2. Open dev tools
3. Visit https://alert-revolver.glitch.me/pathfora.html
4. Note error in console

**Comment by ashyablok** [comment]
@shindakun One thing I noticed a bout the syntax here is that `window.pathfora.initializeWidgets([modules]);` should be `window.pathfora.initializeWidgets(modules);`

**Comment by shindakun** [comment]
@ashyablok good catch! Looks like the error message persists though :(

**Comment by RaeEversmann** [comment]
Looking into this now see, https://lytics.slack.com/archives/CN5K3PQT1/p1685737814145719

**Comment by RaeEversmann** [comment]
also see https://github.com/lytics/jstag3/issues/199

**Comment by RaeEversmann** [comment]
This should be deployed, will close the issue once verified

**Comment by smcmahon42** [comment]
@RaeEversmann I tested in incognito and the first loadEntity worked, after going to a second page the loadEntity hit an error.

 
![Screenshot 2023-06-09 at 11 16 03 AM](https://github.com/lytics/pathforajs/assets/4053510/b5e1fc8b-cbf4-4db8-997b-d21bf3f14e8e)

**Comment by RaeEversmann** [comment]
@smcmahon42 This looks like a different error, can you open a new issue?
