### ISSUE TITLE
Content Recommendation Support (basic)

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#84]
tbd

```
var promoWidget = new pathfora.Message({
  "layout": "modal",
  "variation": 3,
  "msg": "some cool content we know you'll be interested in",
  "recommend": {
    "query": {
      "raw": "FILTER AND (url LIKE 'www.getlytics.com/integrations/*') FROM content"
    },
    "content": [
      {
        "title": "My Page Title",
        "descr": "My page meta description",
        "img": "http://mypageimage.com/woot.jpg",
        "url": "http://google.com"
      }
    ]
  }
});
```

**Comment by sarahyablok** [comment]
Some simple template ideas for v1 of slideout and modal layouts (we will not support button/bar layouts for now):

![v1](https://cloud.githubusercontent.com/assets/5973633/15298589/e342fe10-1b54-11e6-9f65-a7e4d4b76f4b.jpg)

**Some questions/comments:**
To review with @markhayden and @bpatterson88 
- The boxes with the recommendation should be a blocked `<a>` element, so the user may click anywhere on it to proceed.
- User defined image, and buttons are allowed but defaulted to not show.
- Do we want to allow for custom colors on these elements? Assuming for v1 we don't want to over complicate anything the designs above borrow their colors from the existing config, and are subject to change:
  - background of box - `confirmBackground`
  - border of box - `close`
  - content title - `confirmText`
  - content description - `text`
- Anything else we want to display meta wise on these? Author/date? Seems unnecessary for v1.

**Comment by bpatterson88** [comment]
These look pretty good. I think we can just tie the colors to the existing theme config without surfacing them as unique options (which sounds like what you're doing). Any other metadata is probably over complicating it at this point. 

Two design nits:
 - I don't love the border around the content unit. If there's not enough contrast between the border and the image (like in the default theme example) it loses some crispness. I think the colored background would be enough to highlight the content unit.
 - Seems like there's just a bit too much space above the headline on the modals.

**Comment by markhayden** [comment]
agree with @bpatterson88 on the border. we should just make sure the headline / body background has enough contrast to create the separation. i could be wrong but i think with the slideout there is only one variation now. well there are 2 but one is with image and one is without. they all use the tall / skinny format instead of the horizontal. so this would be variation 3 that includes a site overview. 

on the modal, it is probably fine but lets make sure its not giant when its actually rendered. that middle modal tends to be pretty large overall.

**Comment by sarahyablok** [comment]
Cool, getting rid of the borders. You're right about the slideout variants I think I was thinking of the subscriptions for that horizontal one, so I'll proceed with the tall one (the one labeled variant 2 in the image). Thanks guys, will continue to post progress. :)
