### ISSUE TITLE
Lead Capture Fields - WIP

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#90]
As we gather feedback I'd like to make one or two passes through to add optional fields that are commonly requested. This is a placeholder ticket, don't start on it yet.

Add:
* First name
* Last name
* Email
* Message
* Company
* Job Title
* Phone Number

**Comment by sarahyablok** [comment]
Once showing/hiding fields exists in the UI we should probably uniform the fields on the siteGate and form. Currently,

Form has:
- Name
- Title
- Email
- Message

SiteGate has:
- Name
- Email
- Organization
- Title

Seems like we should allow all these fields on either form, and just let the user select which ones they want.

**Comment by markhayden** [comment]
agreed
