### ISSUE TITLE
compare query params unordered

### ISSUE THREAD

**Issue by humanchimp** [lytics/pathforajs#95]
Query params are inherently unordered, so matching criteria should compare them in an unordered way.

`http://www.example.com?foo=1&bar=2` should match `http://www.example.com?bar=2&foo=1`.

Additionally, extra query params should be ignored.

`http://www.example.com?foo=1&bar=2&baz=3` should match `http://www.example.com?bar=2&foo=1`

**Comment by sarahyablok** [comment]
To clarify, it was discussed that we actually do not want to accept extra query params, only that we should ignore the `lytics_variation_preview_id` key in our comparisons. Going to fix this in #99 shortly.
